-- TRIGGER
-- 1. Sinh viên có DTB >= 5 thì đạt và ngược lại 
CREATE TRIGGER CHECK_KQ
ON KETQUA
FOR INSERT, UPDATE
AS
BEGIN
	IF ((SELECT DIEMTB FROM inserted) < 5 AND (SELECT KQUA FROM inserted) = 'Dau')
	BEGIN
			RAISERROR(N'Sinh vien co DTB < 5 thi ket qua phai la Khong dau', 16, 1)
            ROLLBACK TRANSACTION
    END 
	ELSE IF ((SELECT DIEMTB FROM inserted) >= 5 AND (SELECT KQUA FROM inserted) = 'Khong dau')
		BEGIN
			RAISERROR(N'Sinh vien co DTB >= 5 thi ket qua phai la Dau', 16, 1)
            ROLLBACK TRANSACTION
        END
END

-- 1.1 THỰC THI VÀ KIỂM TRA
SELECT * FROM KETQUA
INSERT INTO KETQUA VALUES ('21520001', 'IT001', 2, 9.00, 'Khong dau') -- THẤT BẠI
INSERT INTO KETQUA VALUES ('21520002', 'IT002', 2, 3.50, 'Dau') -- THẤT BẠI
INSERT INTO KETQUA VALUES ('21520002', 'IT002', 1, 3.50, 'Khong dau') -- THÀNH CÔNG
-- 1.2 KHÔI PHỤC DỮ LIỆU
DELETE FROM KETQUA WHERE MSSV = '21520002' AND MAMH = 'IT002' AND LANHOC = 1
-- 1.3 XÓA
DROP TRIGGER CHECK_KQ
GO

-- 2. Ngày bắt đầu (TUNGAY) của 1 lớp phải nhỏ hơn ngày kết thúc (DENNGAY) của lớp đó   
CREATE TRIGGER TGBD_TGKT
ON GIANGDAY
FOR INSERT, UPDATE
AS
BEGIN
	IF ((SELECT TUNGAY FROM inserted) >= (SELECT DENNGAY FROM inserted))
		BEGIN
			RAISERROR(N'Thời gian bắt đầu phải nhỏ hơn thời gian kết thúc môn học', 16, 1)
            ROLLBACK TRANSACTION
        END
END
-- 2.1 THỰC THI VÀ KIỂM TRA
INSERT INTO GIANGDAY VALUES ('IT004.N21', 'GV05', 1, 2022, '07/12/2022', '08/09/2022') -- THẤT BẠI
INSERT INTO GIANGDAY VALUES ('IT004.N21', 'GV05', 1, 2022, '22/09/2022', '01/12/2022') -- THÀNH CÔNG
SELECT * FROM GIANGDAY
-- 2.2 KHÔI PHỤC DỮ LIỆU
DELETE FROM GIANGDAY WHERE MALOP = 'IT004.N21' AND MAGV = 'GV05'
-- 2.3 XÓA
DROP TRIGGER TGBD_TGKT
GO

-- 3. DIEM không được nhỏ hơn 0 hoặc lớn hơn 10
CREATE TRIGGER CHECK_DIEM
ON KETQUA
FOR INSERT, UPDATE
AS
BEGIN
	IF ((SELECT DIEMTB FROM inserted) < 0 OR (SELECT DIEMTB FROM inserted) > 10)
		BEGIN
			RAISERROR(N'Điểm môn học không được nhỏ hơn 0 hoặc lớn hơn 10', 16, 1)
            ROLLBACK TRANSACTION
        END
END

-- 3.1 THỰC THI VÀ KIỂM TRA
INSERT INTO KETQUA VALUES ('21520001', 'IT007', 1, 11.00, 'Dat') -- THẤT BẠI
INSERT INTO KETQUA VALUES ('21520001', 'IT007', 1, 7.50, 'Dat') -- THÀNH CÔNG
SELECT * FROM KETQUA
-- 3.2 KHÔI PHỤC DỮ LIỆU
DELETE FROM KETQUA WHERE MSSV = '21520001' AND MAMH = 'IT007'
-- 3.3 XÓA
DROP TRIGGER CHECK_DIEM
GO

-- CRYSTAL REPORT
-- 1. Tạo report thống kê điểm của sinh viên theo từng môn học 
CREATE VIEW THONGKE_DIEM
AS
	SELECT MH.MAMH, TENMH, SV.MSSV, HOTEN, DIEMTB
	FROM SINHVIEN SV JOIN KETQUA KQT ON SV.MSSV = KQT.MSSV JOIN MONHOC MH ON KQT.MAMH = MH.MAMH
GO

SELECT * FROM THONGKE_DIEM

DROP VIEW THONGKE_DIEM

-- 2. Tạo report thống kê điểm của các sinh viên học lớp IT007.N21
CREATE VIEW BANGDIEM_IT007_N21
AS
	SELECT SV.MSSV, HOTEN, MAKHOA, DIEMTB
	FROM SINHVIEN SV JOIN KETQUA KQT ON SV.MSSV = KQT.MSSV JOIN HOC ON KQT.MSSV = HOC.MSSV
	WHERE MALOP = 'IT007.N21' AND MAMH = 'IT007'
GO

SELECT * FROM BANGDIEM_IT007_N21

DROP VIEW BANGDIEM_IT007_N21
