CREATE DATABASE QuanLyGiaoVu
USE QuanLyGiaoVu

CREATE TABLE SINHVIEN(
	MSSV CHAR(8) PRIMARY KEY,
	HOTEN VARCHAR(40),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	NOISINH VARCHAR(40),
	MAKHOA VARCHAR(4)
)

CREATE TABLE KHOA(
	MAKHOA VARCHAR(4) PRIMARY KEY,
	TENKHOA VARCHAR(40),
	NGTLAP SMALLDATETIME,
	TRGKHOA CHAR(4)
)

CREATE TABLE MONHOC(
	MAMH VARCHAR(10) PRIMARY KEY,
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA VARCHAR(4)
)

CREATE TABLE GIAOVIEN(
	MAGV CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GIOITINH VARCHAR(3),
	NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME,
	HESO NUMERIC(4,2),
	MUCLUONG MONEY,
	MAKHOA VARCHAR(4)
)

CREATE TABLE LOP(
	MALOP VARCHAR(30) PRIMARY KEY,
	SISO TINYINT,
	MAMH VARCHAR(10)
)

CREATE TABLE GIANGDAY(
	MALOP VARCHAR(30),
	MAGV CHAR(4),
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME,
	PRIMARY KEY(MALOP, MAGV)
)

CREATE TABLE KETQUATHI(
	MSSV CHAR(8),
	MAMH VARCHAR(10),
	LANTHI TINYINT,
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KQUA VARCHAR(10),
	PRIMARY KEY(MSSV, MAMH, LANTHI)
)

CREATE TABLE HOC(
	MSSV CHAR(8),
	MALOP VARCHAR(30),
	PRIMARY KEY(MSSV, MALOP)
)

CREATE TABLE DIEUKIEN(
	MAMH VARCHAR(10),
	MAMH_TRUOC VARCHAR(10),
	PRIMARY KEY (MAMH, MAMH_TRUOC)
)

ALTER TABLE SINHVIEN 
ADD CONSTRAINT FK_SINHVIEN_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE KHOA 
ADD CONSTRAINT FK_KHOA_GIAOVIEN FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE MONHOC
ADD CONSTRAINT FK_MONHOC_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GIAOVIEN_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE GIANGDAY 
ADD CONSTRAINT FK_GIANGDAY_GIAOVIEN FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE GIANGDAY 
ADD CONSTRAINT FK_GIANGDAY_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KETQUATHI_SINHVIEN FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV)

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KETQUATHI_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE HOC
ADD CONSTRAINT FK_HOC_SINHVIEN FOREIGN KEY (MSSV) REFERENCES SINHVIEN(MSSV)

ALTER TABLE HOC
ADD CONSTRAINT FK_HOC_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DIEUKIEN_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DIEUKIEN_MONHOCTRUOC FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH)

